import {
  index,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

export const leadSourceEnum = pgEnum('lead_source', ['Website', 'Social Media', 'Email Campaign', 'Cold Call', 'Referral', 'Trade Show', 'Advertisement', 'Other']);
export const leadStatusEnum = pgEnum('lead_status', ['New', 'Contacted', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost']);
export const leadPriorityEnum = pgEnum('lead_priority', ['Low', 'Medium', 'High', 'Hot']);
export const engagementLevelEnum = pgEnum('lead_engagement_level', ['Low', 'Medium', 'High']);

export const leads = pgTable(
  'leads',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    leadId: varchar('leadId', { length: 64 }),
    firstName: varchar('firstName', { length: 255 }).notNull(),
    lastName: varchar('lastName', { length: 255 }).notNull(),
    email: varchar('email', { length: 255 }).notNull(),
    phone: varchar('phone', { length: 64 }).notNull(),
    company: varchar('company', { length: 255 }),
    position: varchar('position', { length: 255 }),
    source: leadSourceEnum('source').notNull(),
    status: leadStatusEnum('status').notNull().default('New'),
    priority: leadPriorityEnum('priority').notNull().default('Medium'),
    interestedProducts: jsonb('interestedProducts').notNull().default([]),
    estimatedValue: numeric('estimatedValue', { mode: 'number' }),
    actualValue: numeric('actualValue', { mode: 'number' }),
    expectedCloseDate: timestamp('expectedCloseDate', { withTimezone: true }),
    actualCloseDate: timestamp('actualCloseDate', { withTimezone: true }),
    assignedTo: uuid('assignedTo').notNull(),
    assignedBy: uuid('assignedBy'),
    meetings: jsonb('meetings').notNull().default([]),
    totalMeetings: numeric('totalMeetings', { mode: 'number' }).notNull().default(0),
    completedMeetings: numeric('completedMeetings', { mode: 'number' }).notNull().default(0),
    upcomingMeetings: numeric('upcomingMeetings', { mode: 'number' }).notNull().default(0),
    nextMeetingDate: timestamp('nextMeetingDate', { withTimezone: true }),
    lastMeetingDate: timestamp('lastMeetingDate', { withTimezone: true }),
    averageMeetingDuration: numeric('averageMeetingDuration', { mode: 'number' }).notNull().default(0),
    notes: jsonb('notes').notNull().default([]),
    lastContactDate: timestamp('lastContactDate', { withTimezone: true }),
    nextFollowUpDate: timestamp('nextFollowUpDate', { withTimezone: true }),
    address: jsonb('address').notNull().default({}),
    wonDetails: jsonb('wonDetails').notNull().default({}),
    leadScore: numeric('leadScore', { mode: 'number' }).notNull().default(0),
    engagementLevel: engagementLevelEnum('engagementLevel').notNull().default('Medium'),
    responseRate: numeric('responseRate', { mode: 'number' }).notNull().default(0),
    tags: jsonb('tags').notNull().default([]),
    customFields: jsonb('customFields').notNull().default({}),
    convertedAt: timestamp('convertedAt', { withTimezone: true }),
    createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    leadIdUniqueIdx: uniqueIndex('leads_leadId_unique_idx').on(table.leadId),
    assignedStatusIdx: index('leads_assignedTo_status_idx').on(table.assignedTo, table.status),
    emailIdx: index('leads_email_idx').on(table.email),
    phoneIdx: index('leads_phone_idx').on(table.phone),
    statusPriorityIdx: index('leads_status_priority_idx').on(table.status, table.priority),
    nextFollowUpDateIdx: index('leads_nextFollowUpDate_idx').on(table.nextFollowUpDate),
    nextMeetingDateIdx: index('leads_nextMeetingDate_idx').on(table.nextMeetingDate),
  }),
);
